### ISSUE TITLE
Morning session code r

### ISSUE THREAD

**Issue by Kwaleyela-Ikafa** [muskan2532150/To-Do-List#5]
# Highlights :star_struck: 

:heavy_check_mark:  No linter errors
:heavy_check_mark: Descriptive Read me

## suggested changes

- please remove commented code from your repository to make your code clean

https://github.com/muskan2532150/To-Do-List/blob/562abab82c0513bda8bb4d0af684f93a994fac75/src/index.js#L36

- please use ES6 arrow functions

https://github.com/muskan2532150/To-Do-List/blob/562abab82c0513bda8bb4d0af684f93a994fac75/src/index.js#L46-L48

**Comment by muskan2532150** [comment]
I have made changes from your review.
